### ISSUE TITLE
Ordinal numbers

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-backlog#100]
This was original part of the work on reviewing numbers: https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/52 
At 5 June Style Council, we agreed to research these further (Readability guidelines) and to check them on assistive tech.

**Comment by mcheung-nhs** [comment]
Tested using this page on VoiceOver (iOS) and JAWS:
https://mcheung-nhs.github.io/accessibility/tests/ordinals.html

Both read them the same except for the superscript version whereby VoiceOver has a weird 'feature' where it pauses when it comes across a HTML element when swiping to the content. So when the code is:

`<p>The 2<sup>nd</sup> time you see a doctor</p>`

it would read:
"The 2" and then you would need to swipe across to hear "n d" and then swipe again to hear "time to see a doctor".

Recommendation is not to use the superscript html element.

"First" and '1st"
"Second" and "2nd"
"Third" and "3rd"
"Fourth" and "4th"

Both read the same so can use either.

**Comment by sarawilcox** [comment]
Agreed at 18 June Style Council meeting that we will use numbers in ordinals (1st, 2nd) but not to use superscript.

**Comment by sarawilcox** [comment]
Page updated in content section.
