### ISSUE TITLE
External link behaviour

### ISSUE THREAD

**Issue by SiRose** [nhsuk/nhsuk-service-manual-backlog#102]
It would be helpful to clarify in the service manual if links to external websites should open in the same tab or window or in a new one and if there are distinct exceptions.

It has always been my understanding and clear from user research that users can be confused by links opening in new tabs or windows, due to damaged usability and orientation. 

There's also significant difference between a new tab and a new window. Control of that might be at browser level, not user level.

It's not always obvious that a new window or tab has opened. Users might not realise they're not in the original window and that they can't navigate back.

The new [apps and wearables guidance pages](https://mhealth.service.nhs.uk/daq.html) currently open links to external sites in a new window. That's partly through that team's choice and partly as it seems to be a default in their Wagtail instance .

I've been reviewing some of their material but I'm starting to work more and more with this team, so I'd like to refer to some clear guidance as evidence of best practice.

I can't find anything about this on the [GOV.UK style guide](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style), which remains hard to search well.

If and when linking to a new tab or window might be the best option, it's best at least to say so, to manage user expectations. When the corporate site had an NWW site for example and we had to link out to it from the WWW site, we used the phrase '(opens in a new window)' in the link text.

**Comment by sarawilcox** [comment]
Thanks, Simon. 
W3C says to limit the use of links or buttons that open new windows or tabs. There are main 2 examples of exceptions: for help instructions or other help with filling in a form (eg a date picker) and if someone's logged into a secure site and the link would terminal their logon. If links do go to a new tab or window, you need to warn the user. (https://www.w3.org/TR/WCAG20-TECHS/G200.html)

Also, I'm working on our accessibility guidance which will be published in the service manual. It says: If links open in a new window, say this in the link phrase. For example, "Link name (opens in new window)".

**Comment by sarawilcox** [comment]
Agreed to follow W3C at 18 June Style Council meeting.

**Comment by sarawilcox** [comment]
Style Council meeting agreed to amend links page: https://beta.nhs.uk/service-manual/content/links-and-pdfs

Add a new heading under Links for External links, with this info: 

Avoid using links or buttons that open new windows or tabs.  

There are 2 exceptions to this:  

- for instructions or other help with filling in a form (for example, a date picker)  

- if a user has logged into a secure site and the link would take them away from it 

Read more about opening new windows and tabs on W3C [link to https://www.w3.org/TR/WCAG20-TECHS/G200.html]. 

If links do go to a new tab or window, warn the user by saying: "Link name (opens in new window)". (Include all of this in the link text.)

**Comment by sarawilcox** [comment]
More about these issues in the [Links - external ticket](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/182).
