### ISSUE TITLE
Tweak wording to microgram

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-backlog#113]

**Comment by sarawilcox** [comment]
Instead of: "If people might come across the microgram symbol, for example on their medicines packet, we add…"​​

Say: "We don't usually use the symbol unless people are likely to see it on their medicines or vitamins packet. In this case, we add ..."

**Comment by sarawilcox** [comment]
Agreed at July Style Council meeting:
Instead of: "If people might come across the microgram symbol, for example on their medicines packet, …", we’re proposing to say: 

"We only use the symbol if people will find it helpful, for example, if they are likely to see it on their medicines or vitamins packet." 
[Waiting for nhs.uk clinical approval.]

**Comment by sarawilcox** [comment]
Approved by clinicians

**Comment by vlj83** [comment]
Updated and sent for approval

**Comment by sarawilcox** [comment]
Thanks for doing this @vlj83. I've realised that the wording isn't quite right. My fault for not being clear enough in the ticket. I'll amend it and then put this into Done.

**Comment by sarawilcox** [comment]
Amended. All fine now.
