### ISSUE TITLE
Slack address on UI style, components and patterns A to Z page

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-backlog#121]
On this page: **https://beta.nhs.uk/service-manual/styles-components-patterns/a-to-z.njk**

Change from:
Join us on the NHS.UK service manual Slack workspace or email us at service-manual@nhs.net

To: 
Join us on the service manual Slack workspace [keep link] or email us at service-manual@nhs.net

**Comment by vlj83** [comment]
Updated and sent for review
