### ISSUE TITLE
Slack address on service manual home page

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-backlog#122]
Change from:
Get in touch
The service manual is maintained by the standards team. Get in touch if you have any questions or feedback.

Slack: NHS.UK service manual Slack workspace [keep link]
Email: service-manual@nhs.net

To:

Get in touch
The manual is maintained by the service manual team at NHS Digital. Get in touch if you have any questions or feedback.

Slack: service manual public Slack workspace [keep link]
Email: service-manual@nhs.net

**Comment by vlj83** [comment]
Updated and sent for review
