### ISSUE TITLE
Inclusive language - heading for Gender and sexuality

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-backlog#139]
For GitHub training 15 August.
On inclusive language page:
https://beta.nhs.uk/service-manual/content/inclusive-language

Change `<h2>Gender and sexuality</h2>` to   ` <h2>Sex, gender and sexuality</h2>`

[Agreed at July Style Council meeting. See #60.]

**Comment by sarawilcox** [comment]
Merged into the staging environment. To be published with next batch of changes.

**Comment by henocookie** [comment]
Notes from this issue copied into #143
