### ISSUE TITLE
Sleepy

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-backlog#147]
**For GitHub training 21 August 2019**

On the A to Z of NHS health writing: https://beta.nhs.uk/service-manual/content/a-to-z-of-NHS-health-writing

Under S, between the terms side effects and smear test, add a new entry for sleepy as follows:

```
<h3 id="sleepy">sleepy</h3>
<p>Generally, we prefer the word "sleepy" to "drowsy" as people are more likely to search for "sleepy". But "<a href="#drowsy">drowsy</a>" may be better if you're writing about feeling unusually sleepy in the daytime, particularly in the context of medicines.</p>
```

[Still subject to final clinical approval.]

**Comment by theonlymojo** [comment]
https://github.com/nhsuk/nhsuk-service-manual/pull/306

**Comment by sarawilcox** [comment]
This is now on staging server. Pending clinical approval.

**Comment by sarawilcox** [comment]
Closing this ticket. It was an update to this main ticket: [Drowsy, sleepy and sedating #76](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/76).
