### ISSUE TITLE
Organisational header

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual-backlog#156]
## What

A variant of the header for other NHS organisations.

## Why

Most NHS organisations use a different [organisational logo](https://www.england.nhs.uk/nhsidentity/identity-guidelines/organisational-logos/).

It would be useful to extend the logo part of the header for those organisations.

This feature was raised by the community in the [NHS.UK frontend](https://github.com/nhsuk/nhsuk-frontend/issues/446).

#### The Leeds Teaching Hospitals

<img width="1439" alt="Screenshot 2019-09-04 at 12 12 00" src="https://user-images.githubusercontent.com/14331000/64250156-4f17e000-cf0d-11e9-9f67-cd218cae3c63.png">

https://www.leedsth.nhs.uk/

#### Bradford Teaching Hospitals

<img width="1440" alt="Screenshot 2019-09-04 at 11 30 29" src="https://user-images.githubusercontent.com/14331000/64250052-124be900-cf0d-11e9-8268-2f3574bc4fb0.png">

https://www.bradfordhospitals.nhs.uk/

#### Great Ormond Street Hospital

<img width="1440" alt="Screenshot 2019-09-04 at 11 30 50" src="https://user-images.githubusercontent.com/14331000/64250053-124be900-cf0d-11e9-97b4-cf9f673b0a10.png">

https://www.gosh.nhs.uk/

#### NHS Leadership Academy

<img width="1440" alt="Screenshot 2019-09-04 at 11 31 20" src="https://user-images.githubusercontent.com/14331000/64250054-124be900-cf0d-11e9-8471-3a1f34fe3b3a.png">

https://www.leadershipacademy.nhs.uk/

#### NHS Digital

<img width="1440" alt="Screenshot 2019-09-05 at 12 00 03" src="https://user-images.githubusercontent.com/14331000/64336483-fad83300-cfd4-11e9-96e0-d13f559d949f.png">

https://digital.nhs.uk/

**Comment by davidhunter08** [comment]
![org-header-png](https://user-images.githubusercontent.com/14331000/64335798-7802a880-cfd3-11e9-8a4b-c69771e349d7.png)

![org-header](https://user-images.githubusercontent.com/14331000/64335802-789b3f00-cfd3-11e9-8c06-6f74a38ea85e.png)

![org-header-white-nav](https://user-images.githubusercontent.com/14331000/64335800-7802a880-cfd3-11e9-8d1a-8add134078d1.png)

![org-header-white](https://user-images.githubusercontent.com/14331000/64335801-7802a880-cfd3-11e9-92e7-b7fa0bd453f3.png)

**Comment by theonlymojo** [comment]
We discussed this component as part of a design working group in NHS Digital. We agreed we'll soon have the Organisational header in the digital service manual and mark it as 'experimental' whilst people try and adopt the component.

If you use this component, please share your work and any user feedback within this GitHub issue.

**Comment by theonlymojo** [comment]
We've published guidance about the organisational header in the service manual - 
https://beta.nhs.uk/service-manual/styles-components-patterns/header#organisational-header

We've labelled it as **experimental** as we want more examples and research of it working and fulfilling user needs.

Moving this issue to *published* but please do keep contributing within this thread as and when you have evidence of using the organisational header.

**Comment by AdamChrimes** [comment]
We need to add guidance around the white header with a white navigation variant. The current example shows a white header with a blue navigation.

You can see this example here: https://nhsuk.github.io/nhsuk-frontend/components/header/header-org-white-nav.html

`nhsuk-header--white nhsuk-header--white-nav `

**Comment by AdamChrimes** [comment]
Should we have a variant for organisational header with a service name?

**Comment by davidhunter08** [comment]
Closing this issue as the organisational header is a variant of the [header component](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/16)
