### ISSUE TITLE
Error messages in radios and checkboxes

### ISSUE THREAD

**Issue by JackMatthams** [nhsuk/nhsuk-service-manual-backlog#180]
## What
> We currently follow GOV.UK guidance on how to phrase error messages on both radios and checkboxes. Our revised guidance uses these examples:
> - "Select yes if you have changed your name" for radios
> - "Select if you have 1 of these conditions" for checkboxes

## Why
> We have concerns that the example radio error message is leading, and the example checkbox message is unclear as to how many boxes people should select, and what they should do if they apply to a 'none' or 'other' box. They both go against other current guidance.
> Suggested improvements for checkbox error messages include:
> - "Select all of the conditions you have, or select none"
> - "Select the conditions you have, or select none"
>
> Suggested improvements for radio error messages include:
> - "You need to tell us if you have changed your name"
> - "Tell us if you have or have not changed your name"
> - "Select an option to tell us if you have changed your name, or not"
> - "Select if you have or have not changed your name"

## Anything else
> We are contacting GOV to ask about their reasoning behind phrasing the radio and checkbox error messages like this. 
> We are also conducting research into this.
> We plan to bring this to a future content style council. 
>
> GOV.UK's guidance on radio error messages: 
> ![gov uk radio error message](https://user-images.githubusercontent.com/55354859/68669236-f59de400-0541-11ea-8dbf-888a485432e0.png)
> https://design-system.service.gov.uk/components/radios/#error-messages
>
> GOV.UK's guidance on checkbox error messages:
> ![gov uk checkbox error message](https://user-images.githubusercontent.com/55354859/68670034-d1430700-0543-11ea-9d20-7e87aafcaa3f.png)
> https://design-system.service.gov.uk/components/checkboxes/
>
> Our current guidance on radio error messages can be seen here: 
> ![Screenshot 2019-11-06 at 17 08 20](https://user-images.githubusercontent.com/55354859/68669416-5a593e80-0542-11ea-9581-a38fa290370c.png)
> https://beta.nhs.uk/service-manual/styles-components-patterns/radios
>
> Our current guidance on checkbox error messages can be seen here: 
> ![Screenshot 2019-11-06 at 17 06 44](https://user-images.githubusercontent.com/55354859/68669445-71982c00-0542-11ea-83a7-07bbc57ed792.png)
> https://beta.nhs.uk/service-manual/styles-components-patterns/checkboxes

**Comment by sarawilcox** [comment]
I'm trying to rationalise the backlog and have captured these details in this ticket instead: https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/12. We're hoping to do more work on error messages in the next few months.
