### ISSUE TITLE
Example of an error summary and an error message working together

### ISSUE THREAD

**Issue by samanthasaw** [nhsuk/nhsuk-service-manual-backlog#189]
## What
> As well as having separate guidance for error summaries and error messages, show an example of the two components working together

## Why
> - I'm struggling to get the link in the error summary to move to focus on the error message
> - GOV Design system shows an example with the two components together: [https://design-system.service.gov.uk/components/error-summary/]
> - Can't see that this already exists in the manual

**Comment by AdamChrimes** [comment]
This came up on a coronavirus project I am working on, we could have done with some examples of these functioning and the code for them.

+1 for needing this.

**Comment by davidhunter08** [comment]
The [error summary page](https://service-manual.nhs.uk/design-system/components/error-summary) was recently updated with more examples.

The [error message page](https://service-manual.nhs.uk/design-system/components/error-message) only has a date input example so more examples are probably needed.

**Comment by AdamChrimes** [comment]
@davidhunter08 I think having some examples (and maybe even code snippets) for the focusing error summary and linking from error summary to error messages would be useful. Similar to GOVUK https://design-system.service.gov.uk/components/error-summary/#linking-from-the-error-summary-to-each-answer

I think this has tripped a few teams up (including my recent project)

**Comment by davidhunter08** [comment]
The error message page now includes examples of the error summary and error message working together.
