### ISSUE TITLE
Months up to 2 years

### ISSUE THREAD

**Issue by JackMatthams** [nhsuk/nhsuk-service-manual-backlog#198]
## What
> We currently use the number of months to describe age up to 2 years, for example "14 months". We want to put some guidance into the service manual to explain why we do this instead of giving an approximate age in years. 

## Why
> We believe most users speak of their child's age in months. 

>On the inclusive language page, we currently say: 
> "With babies and toddlers, we count their age in weeks up until 6 months, then months up until. 2 years."

> We propose to add: 
> "Our research shows that this is how people tend to talk about their child's age. It also helps to be specific when talking about a baby's milestones, vaccinations and development reviews."

**Comment by sarawilcox** [comment]
We had some Twitter feedback, asking us to explain why, in the style guide, we say: “With babies and toddlers, we count their age in weeks up until 6 months, then months up until 2 years.” 

At the January 2020 Style Council meeting, we talked about the following explanation: “This is how people tend to talk about their child's age. It also helps to be specific when writing about a baby's milestones, vaccinations and development reviews.” 

People commented that it’s not just users but healthcare professionals and the Red Book that refer to age in this way.   

Proposed note to go on inclusive language page - it's been approved by clinicians: 

"Our research shows that this is how people talk about their child's age. Healthcare professionals also use weeks and months in this way. It means we can be consistent and accurate when writing about a baby's milestones, vaccinations and development reviews."

**Comment by sarawilcox** [comment]
Published. https://service-manual.nhs.uk/content/inclusive-language

**Comment by sarawilcox** [comment]
The content of this ticket has been included in [Inclusive language: Age](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/142). Am closing this ticket down.
