### ISSUE TITLE
Dental surgery or practice

### ISSUE THREAD

**Issue by JackMatthams** [nhsuk/nhsuk-service-manual-backlog#215]
## What
Should we always refer to dental surgery rather than dental practice - as we do for GP surgery? At the moment we use both terms for dentists and it is inconsistent. 

## Why
No direct user testing of this, but in user testing labs of the dental profiles on nhs.uk, users seemed to understand and use the term 'GP surgery' more than 'GP practice'.

## Anything else
Link to ticket on GP surgery or practice: https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/168

**Comment by sarawilcox** [comment]
We have a duplicate ticket [Dentist or dental surgery or practice #229](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/229), so I'm closing this one down.
