### ISSUE TITLE
Error message - more examples of inputs

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-service-manual-backlog#222]
## What

The [error message page](https://service-manual.nhs.uk/design-system/components/error-message) only has 1 example of the date input component with errors. It would be useful if there were multiple examples of different input types (text input, text area, select etc). As the date input is multiple fields and may cause confusion.

**Comment by davidhunter08** [comment]
[JIRA 1684](https://jira.service.nhs.uk/browse/STAN-1684)
