### ISSUE TITLE
Update guidance on input type="number"

### ISSUE THREAD

**Issue by AdamChrimes** [nhsuk/nhsuk-service-manual-backlog#223]
https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

**Comment by davidhunter08** [comment]
[JIRA 1682](https://jira.service.nhs.uk/browse/STAN-1682)

**Comment by mcheung-nhs** [comment]
https://design-system.service.gov.uk/components/text-input/#numbers
