### ISSUE TITLE
Softer voice and tone for mental health related service content

### ISSUE THREAD

**Issue by beccagorton182** [nhsuk/nhsuk-service-manual-backlog#245]
## What
> Softening the voice and tone of content for services that are for people who have a mental health condition (or care for somebody who has a mental health condition)

## Why
> There currently isn't any specific guidance about slightly softening voice and tone for this user group. But altering the voice and tone is referenced here https://service-manual.nhs.uk/content/voice-and-tone
> We have created and tested new pages and services for this user group and have found that users respond well to softer content that uses words like 'please' and more reassuring content like 'you're not bothering anyone' etc. 
> We have tested the new mental health helpline finder with around 25 users and most have responded well to softer and longer H1 form questions, rather than short questions. 
> Users have also responded well to reassurance, and using words they would use, rather than triggering words like 'crisis'. 
> There are other teams working on mental health services at the moment 

## Anything else
> This has been fed back to Barnardos who are working with Snook on a designing for mental health pattern library https://www.designpatternsformentalhealth.org/pattern-library

Will also link to a designing for cognitive load issue when I've made one! 👍

**Comment by beccagorton182** [comment]
We had a particular issue with our H1 form questions. 
We originally had this, but it proved quite triggering for users
![IMG_2326](https://user-images.githubusercontent.com/52791357/83133229-75546000-a0da-11ea-8126-223ac645728f.PNG)

We went with this as it tested well but wasn't the best in terms of following service manual guidance
![IMG_2330](https://user-images.githubusercontent.com/52791357/83133308-987f0f80-a0da-11ea-97de-dee29e5573bc.PNG)

We're going to test with 
![Screenshot 2020-05-26 at 15 52 25](https://user-images.githubusercontent.com/52791357/83133358-aaf94900-a0da-11ea-926d-6f54a30f0484.png)

**Comment by sarawilcox** [comment]
Closing this ticket. Have added the content into the ticket for ["Mental health", "mental illness" and tone for mental health content](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/244).
