### ISSUE TITLE
Icons 

### ISSUE THREAD

**Issue by bencullimore** [nhsuk/nhsuk-service-manual-backlog#264]
## What
https://digital.nhs.uk/blog/transformation-blog/2019/icons-avoid-temptation-and-start-with-user-needs

## Why
On the NHS website redesign, we found that icons didn’t help the user understand the importance as icons can be subjective (different meanings to different people). 

We also heard worrying things like - "oh, I’d just ignore/skip anything with an icon" as they associated it with banner ads.

The best thing for users of the website was spelling out “This is actually quite urgent info” in the form of a prominent heading (see care cards/warning callouts) - as we found users scanning information via headings.

## Anything else
These findings are from the context of icons on pages of health information. It would be great to understand how they work in different contexts, transactional services etc.

**Comment by Fenwick17** [comment]
With @RichFlick we recently ran some user testing sessions for the profiles editor. Within that there was a task to edit 'Easter Sunday' opening times. Generally people assume it is a bank holiday, so we needed a way to inform the user Easter Sunday is not a bank holiday
To do this we opted for using the [govuk warning text](https://design-system.service.gov.uk/components/warning-text/)
![image](https://user-images.githubusercontent.com/11258920/92727123-9037a100-f366-11ea-95a1-3b4b91aebe7b.png)
During the user research testing we found a number of the participants noticed this and then followed the link within the warning text to take them to the appropriate area. 

As well as this we are currently using it on the profile viewer pages to tell a user that a GP is not accepting patients.
![image](https://user-images.githubusercontent.com/11258920/92727272-bfe6a900-f366-11ea-8322-9b7853fc40f3.png)
Again this tested well and users did indeed notice the warning, though there might be future alterations to the content of this.

**Comment by sarawilcox** [comment]
Hi @Fenwick17, did you try the NHS.UK warning callout?

**Comment by Fenwick17** [comment]
@sarawilcox No we didn't test the standard NHS one in this scenario (we are using it for Coronavirus though). We felt the NHS.UK warning callout took up too much space to what was needed and using the GOV.UK approach would work as an alternative.

**Comment by davidhunter08** [comment]
Closing issue due to it being closely related to https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/4
