### ISSUE TITLE
Content and screen readers research

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-backlog#305]
## What

We'd like to test various content scenarios on screen readers, share findings and make decisions based on that. For example, identifying if screen reader users experience any issues with hyphens and dashes or pronunciation.

## Why

We don't know to what extent different content scenarios cause screen reader users problems. Broadly speaking, the advice we've had is not to change what's grammatically correct in order to cater for screen reader users. There are several reasons for this.

- Different screen readers announce punctuation in different ways, and users have control over how punctuation is announced. This means you don’t know how someone will experience your punctuation.​
- Some screen reader users listen incredibly quickly so punctuation will sound very different.​
- Screen reader users will be used to hearing how hyphens, for example, are announced on there particular screen reader(s).
- Screen reader users are able to go back to and interrogate a word or punctuation that they haven’t understood.

However, we don't know for certain whether there are any content style areas where we could provide a better experience for screen reader users.

## Related issues
- [components and headings](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/301)
- the [inset text issue](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/18)
- the [pronunciation issue](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/298)
- [hint text](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/17)
- [hyphens or spaces](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/206)

**Comment by sarawilcox** [comment]
Service manual team is meeting with Alistair for an initial discussion on 3 Feb.

**Comment by mcheung-nhs** [comment]
Some testing pages here for screen readers:
https://github.com/mcheung-nhs/accessibility/tree/master/docs/tests

**Comment by sarawilcox** [comment]
Details of discussions and next steps are recorded in the issues for the components noted above. I'm going to close this ticket t avoid duplication.
