### ISSUE TITLE
PDFs and other non-HTML documents

### ISSUE THREAD

**Issue by Tosin-Balogun** [nhsuk/nhsuk-service-manual-backlog#323]
Use this issue to discuss [PDFs and other non-HTML documents in the service manual](https://service-manual.nhs.uk/content/pdfs-and-other-non-html-documents)

**Comment by sarawilcox** [comment]
There is already an [issue for the PDF guidance page](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/161), so I'm closing this ticket.
