### ISSUE TITLE
Add info about OK being OK for screen readers

### ISSUE THREAD

**Issue by sarawilcox** [nhsuk/nhsuk-service-manual-backlog#54]
We have now tested 'OK' with screen readers. Add this to the A to Z.

**Comment by markasrobinson** [comment]
Comment from Michael Cheung:

"Voiceover pronounces both ‘OK’ and ‘okay’ the same (as you would expect) so I think it’s OK to use OK".

Might need testing with other screen readers too though?

**Comment by sarawilcox** [comment]
@mcheung-nhs, when you have a mo, would you mind checking 'OK' in some other assistive techs please? Just checking that we are OK to use 'OK'. Thanks very much.

**Comment by sarawilcox** [comment]
Agreed at 5 June Style Council, we'll add the info about screen readers to the content style guide. @mcheung-nhs is double checking.

**Comment by mcheung-nhs** [comment]
It is pronounced the same on JAWS and on VoiceOver.
Test page used:
https://mcheung-nhs.github.io/accessibility/tests/ok.html

**Comment by sarawilcox** [comment]
Published an update to A to Z of NHS health writing.
