### ISSUE TITLE
Inclusive language page - including sex, gender and age

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual-backlog#60]
### Latest

Do we use "people with a cervix", "people with a prostate"?

### Already dealt with
Some people have raised questions about the age section on the Inclusive language page of the content style guide.

For example: 
- embryo: from 2 to 9 weeks
- unborn baby: from week 10 to birth
- infant: under 2 years
- toddler: 1 to 3 year
- older person: 60 to 70 years
- elderly person: over 70 years

Do these reflect our latest thinking?

**Comment by sarawilcox** [comment]
Hi @ericlamarca, this isn't right. We've got someone reviewing the Inclusive language page. Hopefully it'll come to the May content Style Council meeting. Do you know what the questions were?

**Comment by sarawilcox** [comment]
In Jira at SS-356.

**Comment by sarawilcox** [comment]
We should capture the conversations around asking questions about sex/gender and age too. See Slack conversation in content channel 30 May.

**Comment by sarawilcox** [comment]
We're making final changes to agree proposals following the July Style Council meeting.

**Comment by sarawilcox** [comment]
Awaiting clinical approval.

**Comment by sarawilcox** [comment]
We have clinical approval. The outcomes of this ticket have been captured in the above tickets. We'll make the changes as part of the 15 August GitHub training. Now closing this issue.

**Comment by sarawilcox** [comment]
We're taking the last bit of 'Age' forward in the ticket for fetus and baby: #136

**Comment by sarawilcox** [comment]
We need to review the page in the light of recent feedback, including comments on Twitter. To come back to the October Style Council meeting?

**Comment by sarawilcox** [comment]
Revised content to be discussed at November 2019 Style Council meeting.

**Comment by sarawilcox** [comment]
Consulted on revised content. Approved at November Style Council meeting, with clinical approval. Now published in style guide: https://beta.nhs.uk/service-manual/content/inclusive-language

**Comment by henocookie** [comment]
Notes from this issues copied into #143
