### ISSUE TITLE
Health professionals and 'specialist teams'

### ISSUE THREAD

**Issue by ericlamarca** [nhsuk/nhsuk-service-manual-backlog#80]
It will help content designers if we can be clear what our preferred terms/usage is. Do we use the shorter "health professional" or the longer "healthcare professional" as a general term for clinicians? Or something else? Please have a word with Martine who raised the issue. She suggests the shorter version.

Also, we agreed at the March 2019 Style Council meeting, that 'healthcare team' was a good term but haven't agreed whether or not we would say, where appropriate, that it might be called a multi-disciplinary team or MDT. We agreed that we needed to research whether users will come across the term. 

An initial internet search suggests that patients with diabetes or cancer may be seen by an MDT - and may need to understand what a multi-disciplinary team is. 

Interestingly, in terms of cancer, some hospitals talk about 'specialist teams' or 'teams of specialist doctors and nurses'.  Should we add that as a phrase we'd use?

Also there was a suggestion at the Style Council meeting that we should make multidisciplinary team one word, but I wonder whether the hyphen helps people who find reading hard?

We have a Jira ticket: SS-400.

**Comment by sarawilcox** [comment]
Closing this ticket down. Taking forward these issues under ticket #49.
