### ISSUE TITLE
Care cards

### ISSUE THREAD

**Issue by ReshmaGumani** [nhsuk/nhsuk-service-manual-backlog#84]
The way we use care cards across NHS.UK is not consistent. 

Many have too many CTAs and conditions in the header and are difficult to read.

An audit of medicines A to Z found 7 variations. 

We need to edit these care cards so they are consistent and clear. 
![image](https://user-images.githubusercontent.com/49678177/56374534-5018d100-61fb-11e9-91aa-0e0e00c8d4ed.png)

JIRA: [MIB-2190]

**Comment by sarawilcox** [comment]
Agreed some initial wording to add to the Care card component at 18 June Style Council meeting. 
But care cards need further work. To come back to July meeting?

**Comment by sarawilcox** [comment]
I've added details from this issue to the [main care cards issue](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/8) and am now closing this ticket.
