### ISSUE TITLE
Headings with captions

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual-backlog#90]
## What

Headings with captions are in the NHS.UK frontend and used on NHS.UK but there is no documentation on how / when to use them.

<img width="697" alt="Screenshot 2019-05-21 at 13 56 10" src="https://user-images.githubusercontent.com/14331000/58097854-3e4a9500-7bd0-11e9-8ce9-a015e293ab7c.png">

https://www.nhs.uk/conditions/age-related-macular-degeneration-amd/

**Comment by sarawilcox** [comment]
@davidhunter08 What are headings with "captions"? (I think of image captions.)

**Comment by davidhunter08** [comment]
Closing issue as it is the same as [issue 178](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/178).
