### ISSUE TITLE
Promo

### ISSUE THREAD

**Issue by davidhunter08** [nhsuk/nhsuk-service-manual-backlog#91]
## What

A promo is a snippet of content which links to the full piece elsewhere on the NHS site or app.

The promo in the NHS.UK frontend is used on NHS.UK but how / when to use is not documented.

<img width="525" alt="Screenshot 2019-05-21 at 14 01 42" src="https://user-images.githubusercontent.com/14331000/58098247-098b0d80-7bd1-11e9-8a26-755f5d754b61.png">

<img width="986" alt="Screenshot 2019-05-21 at 14 01 55" src="https://user-images.githubusercontent.com/14331000/58098253-0bed6780-7bd1-11e9-81a2-e0af2eebb7fb.png">

<img width="986" alt="Screenshot 2019-05-21 at 14 02 03" src="https://user-images.githubusercontent.com/14331000/58098262-10198500-7bd1-11e9-95e6-796717af4976.png">

### Live examples

NHS.UK homepage
https://www.nhs.uk

NHS.UK type 1 diabetes
https://www.nhs.uk/conditions/type-1-diabetes/

**Comment by davidhunter08** [comment]
NHS.UK also uses a different variant of the 'Promo' which is not in the NHS.UK frontend.

<img width="697" alt="Screenshot 2019-05-21 at 14 08 07" src="https://user-images.githubusercontent.com/14331000/58098689-03e1f780-7bd2-11e9-82a9-b4844b0f5535.png">

https://www.nhs.uk/about-us/

**Comment by davidhunter08** [comment]
A promo is very similar to a [panel](https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/159) and we are currently looking at merging the two components into one component with variants.

**Comment by alexparsons07** [comment]
The Design Working Group discussed this issue on 21/10/19. Feedback as follows: 

- Combine the two in the service manual so that they don't overlap and cause confusion. 

- Design working group approved to develop guidance.

**Comment by danjohnstonUX** [comment]
We've used a variation of this on the Summary Care Record application redesign but I haven't pushed any feedback up until now as I think they still need some work in terms of accessibility etc. but they did test very well with our users. There's an example of our variations at http://scra-redesign.herokuapp.com/bna-v4/select-role 

The context of use is that, when logging in, many users will have several roles with differing access rights assigned to their smartcard/identity. We wanted a way that users could quickly select the relevant role for their work, whilst also providing a mechanism for them to view the permissions for that particular role. This has tested well with our users so far across a variety of professions but I'd be happy to start some conversations around how we could improve our version, as I'm in no doubt there's work to be done!

We also created a 'hot ribbon' component which is based on the code for a default promo but amended for our needs. I've discussed this in more detail on issue https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/175

**Comment by mikemonteith** [comment]
Wifi portal post-authentication landing page uses panels:
https://www.nhs.uk/captive-wifi-portal/post-auth/

**Comment by LydiaTeebay** [comment]
We use this element for the [NHS login help centre](https://nhsdigital.github.io/nhs-login-help-centre/) and it's proved to work well in testing (what minimal testing we have done so far).

**Comment by LydiaTeebay** [comment]
<img width="1192" alt="Screenshot 2020-04-02 at 16 19 54" src="https://user-images.githubusercontent.com/50911860/78266545-d9eda700-74fd-11ea-8009-f045890ef946.png">
<img width="1141" alt="Screenshot 2020-04-02 at 16 20 03" src="https://user-images.githubusercontent.com/50911860/78266553-dc500100-74fd-11ea-80a8-20a2dfb19da5.png">

**Comment by AdamChrimes** [comment]
NHSX website uses Promo components quite abit https://www.nhsx.nhs.uk & https://www.nhsx.nhs.uk/key-information-and-tools

**Comment by bencullimore** [comment]
I've written up a variant of the promo component called a 'canonical' link. Based on the needs of the information architecture work https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/254

**Comment by davidhunter08** [comment]
Closing due to the new release of the new [card component](https://service-manual.nhs.uk/design-system/components/card). The card component has replaced the Promo and Panel components. https://github.com/nhsuk/nhsuk-service-manual-backlog/issues/159
