### ISSUE TITLE
Rules for content modularisation

### ISSUE THREAD

**Issue by markasrobinson** [nhsuk/nhsuk-service-manual-backlog#97]
To discuss:

- rules we need to apply to content to make it more suitable for modularisation

**Comment by markasrobinson** [comment]
@sarawilcox I've been thinking about this and I'm not sure if it's really suitable for the service manual.

The guidance is very NHS.UK (and Wagtail) specific - so unlikely to be useful for the wider service manual audience.

Happy to discuss.

**Comment by sarawilcox** [comment]
Thanks Mark. That's OK. I'll close the ticket.
